app/build.gradle.kts
lib/build.gradle.kts
lib/src/main/java/com/cexup/ui/corporate/component/BarChartPatient.kt
lib/src/main/res/values/strings.xml

- now uses string from resource instead of hard-coded strings

refactor: BarChartPatient

---

lib/src/main/java/com/cexup/ui/corporate/screen/ScreenBloodPressure.kt

- moved list entry to data class
- renamed from BloodPressureData to BloodPressureDataUIState

refactor: ScreenBloodPressure

---

lib/src/main/java/com/cexup/ui/corporate/screen/ScreenBodyMassIndex.kt

Reference: #30 
- now uses data class ui state instead of primitives in screen

refactor: ScreenBodyMassIndex

---

lib/src/main/java/com/cexup/ui/corporate/screen/ScreenDoctors.kt

Reference: #33  
- now uses data class for UI state
- some hard-coded strings now use stringResource

refactor: ScreenDoctors

---

lib/src/main/java/com/cexup/ui/corporate/screen/ScreenPatientProfile.kt

Reference #35 
- now uses data class for UI state
- now uses stringResource for hard-coded strings

refactor: ScreenPatientProfile

---

lib/src/main/java/com/cexup/ui/corporate/screen/ScreenPatients.kt

Reference: #36 
- changed from PatientData to PatientProfileUIState

refactor: ScreenPatients

---

lib/src/main/java/com/cexup/ui/corporate/screen/ScreenCheckup.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenDashboard.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenDoctors.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenLogin.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenPatientProfile.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenPatients.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenQuestionnaire.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenRegisterPatient.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenReport.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenTemperature.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenUsg.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenWaist.kt

Reference: #47 
- from dp to dp.from(ctx)
- from sp to sp.from(ctx)

refactor: Size use MediaQuery

---

lib/src/main/java/com/cexup/ui/corporate/screen/ScreenWaist.kt
lib/src/main/res/values/strings.xml

refactor: pageScreenWaist

---

lib/src/main/java/com/cexup/ui/corporate/component/DialogInputManualCheckUp.kt

- missing import: com.cexup.ui.utils.mediaquery.from

fix: DialogInputManualCheckUp

---

app/src/main/java/app/trian/socialapp/MainActivity.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenCheckup.kt

- userCode not set to selected patient

fix: ScreenCheckup

---

lib/src/main/java/com/cexup/ui/corporate/component/CardDoctor.kt
lib/src/main/java/com/cexup/ui/corporate/component/CardMedicalInspection.kt
lib/src/main/java/com/cexup/ui/corporate/component/CardPatientList.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenBodyMassIndex.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenCheckup.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenDoctors.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenPatientProfile.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenPatients.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenQuestionnaire.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenTemperature.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenWaist.kt

refactor: screen Patients, screen doctors, temperature, waist, bmi, checkup,patient profile

---

lib/src/main/java/com/cexup/ui/corporate/component/DialogSelectDevice.kt

#60 
- missing mac address in device row

fix: DialogSelectDevice

---

app/src/main/java/app/trian/socialapp/MainActivity.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenWaist.kt

- missing list label in chart view
- clear main activity content

fix: ScreenWaist

---

lib/build.gradle.kts

fix: lib gradle

---

.github/workflows/build.yml

- changed repo name from Maven to Cexup

fix: build CI

---

lib/src/main/java/com/cexup/ui/corporate/component/DropDownCorporate.kt

fix: DropDownCorporate

---

app/src/main/java/app/trian/socialapp/MainActivity.kt
buildSrc/src/main/java/Publish.kt
lib/src/main/java/com/cexup/ui/corporate/component/CardGlucose.kt
lib/src/main/java/com/cexup/ui/corporate/component/CustomChartMarkerGlucose.kt
lib/src/main/java/com/cexup/ui/corporate/component/DialogDetailsGlucose.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenGlucose.kt
lib/src/main/res/layout/layout_marker_chart_glucose.xml
lib/src/main/res/values/strings.xml

fix: condition in custom marker chart and details

bump: alpha18

---

app/src/main/java/app/trian/socialapp/MainActivity.kt
buildSrc/src/main/java/Publish.kt
lib/src/main/java/com/cexup/ui/corporate/component/CardGlucose.kt
lib/src/main/java/com/cexup/ui/corporate/component/DialogEditMealTypeGlucose.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenGlucose.kt
lib/src/main/res/values/strings.xml

feat: edit Mealtype in Glucose Corporate

---

buildSrc/src/main/java/Publish.kt
lib/src/main/java/com/cexup/ui/corporate/component/CardUsg.kt
lib/src/main/java/com/cexup/ui/corporate/component/CardUsgDetail.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenDetailUsg.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenUsg.kt

refactor: screenusg and screendetailusg nullable and wrong height

---

buildSrc/src/main/java/Publish.kt
lib/src/main/java/com/cexup/ui/corporate/component/CardUsgDetail.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenDetailUsg.kt

feat: shimmer in usg detail

---

buildSrc/src/main/java/Publish.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenDetailUsg.kt

bump: alpha30

---

buildSrc/src/main/java/Publish.kt
lib/src/main/java/com/cexup/ui/corporate/component/CardBabyWeight.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenBabyWeight.kt
lib/src/main/res/drawable/ic_legend_baby_bmi.xml
lib/src/main/res/values/strings.xml

refactor: screen babyweight

---

buildSrc/src/main/java/Publish.kt
lib/src/main/java/com/cexup/ui/corporate/component/CardBabyChartGrowth.kt
lib/src/main/java/com/cexup/ui/corporate/component/CardBabyWeight.kt
lib/src/main/java/com/cexup/ui/corporate/component/ChartBabyGrowth.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenBabyWeight.kt

refactor: change babyBMI double to string, change max axis in babyChart

---

buildSrc/src/main/java/Publish.kt
lib/src/main/java/com/cexup/ui/corporate/component/CardBabyChartGrowth.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenBabyChartGrowth.kt

feat:shimmer card baby chart growth

---

app/src/main/java/app/trian/socialapp/MainActivity.kt
buildSrc/src/main/java/Publish.kt
lib/src/main/java/com/cexup/ui/corporate/component/AppBar.kt
lib/src/main/java/com/cexup/ui/corporate/component/CardUsg.kt
lib/src/main/java/com/cexup/ui/corporate/screen/BaseScreen.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenAccount.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenCheckup.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenDashboard.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenPatients.kt
lib/src/main/java/com/cexup/ui/corporate/theme/Color.kt
lib/src/main/res/values/strings.xml

refactor: New Design Screen List Patient

bump: Alpha43

---

buildSrc/src/main/java/Publish.kt
lib/src/main/java/com/cexup/ui/corporate/component/AppBar.kt
lib/src/main/java/com/cexup/ui/corporate/component/CardDashboard.kt
lib/src/main/java/com/cexup/ui/corporate/component/CardPatientInFeature.kt
lib/src/main/java/com/cexup/ui/corporate/component/CardPatientProfile.kt
lib/src/main/java/com/cexup/ui/corporate/component/ContentSearch.kt
lib/src/main/java/com/cexup/ui/corporate/component/DialogInputManualCheckUp.kt
lib/src/main/java/com/cexup/ui/corporate/component/PieChartDashboard.kt
lib/src/main/java/com/cexup/ui/corporate/screen/BaseScreen.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenDashboard.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenPatientChartExtend.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenPatientProfile.kt
lib/src/main/res/values/strings.xml

fix: padding in chart Pie, contentSearch
feat: screenPatient Chart extend
refactor: add on action done close keyboard in manual input, add a few padding in appbar and change icon in search content

bump: alpha45

---

buildSrc/src/main/java/Publish.kt
lib/src/main/java/com/cexup/ui/corporate/component/AppBar.kt
lib/src/main/java/com/cexup/ui/corporate/component/CardDashboard.kt
lib/src/main/java/com/cexup/ui/corporate/component/CardPatientProfile.kt
lib/src/main/java/com/cexup/ui/corporate/component/DialogFailedCorporate.kt
lib/src/main/java/com/cexup/ui/corporate/component/SearchPatientNew.kt
lib/src/main/java/com/cexup/ui/corporate/component/TabView.kt
lib/src/main/java/com/cexup/ui/corporate/screen/BaseScreen.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenDashboard.kt
lib/src/main/java/com/cexup/ui/corporate/screen/ScreenGlucose.kt
lib/src/main/res/values/strings.xml

fix: 
- not update UI, when data update from viewmodel at CardPatientProfile
- bug UI not update and strings going 2 line in TabView at alpha45
- Overlap size child TabView Glucose
refactor:
-  dialog failed corporate now showing failed data and reason fail
- Search textfield now send value when enter pressed at device keyboard

bump: alpha46
